### ISSUE TITLE
Do not allow only a number for the font size

### ISSUE THREAD

**Issue by bwmarkle** [BoldGrid/crio#112]
If "36" is added:
![image](https://github.com/BoldGrid/crio/assets/5925563/34cf461f-5266-46a7-8126-cf0c2cf7b24d)

The font ends up much smaller.
![image](https://github.com/BoldGrid/crio/assets/5925563/823e220f-c07b-4684-9ee9-6d37b4775515)

**Comment by nicolepaschen** [comment]
When I hover on the Site Title with the Customizer open the :hover doesn't get the px added and the font size changes:

![site-title-hover](https://github.com/BoldGrid/crio/assets/20601160/52f0d9e0-4564-4a36-bcdf-638e63533a81)

**Comment by nicolepaschen** [comment]
When I enter a number without px or em in a menu, the font size does not update in the live preview - the px doesn't get added until the Customizer is published then I see it on the front end correctly.

**Comment by nicolepaschen** [comment]
When there's a Site Title in a CPH (and probably footer) and just a number is entered, the live preview doesn't show me the correct size (not adding px)

**Comment by nicolepaschen** [comment]
I changed heading font size to a number without px added. After closing the Customzier the heading font changed to Source Sans Pro. When I reopen the Customizer and change the font, it doesn't stay changed it goes back to Source Sans Pro no matter what I do after saving and closing the Customizer.
![cannot-change-heading-font](https://github.com/BoldGrid/crio/assets/20601160/1d6e80c6-b45e-45c6-a725-6068eefc6dad)
