### ISSUE TITLE
Padding-right: 10px is added to elements on the front end throwing off alignments

### ISSUE THREAD

**Issue by nicolepaschen** [BoldGrid/crio#23]
This is messing up some of my designs: 
![code](https://user-images.githubusercontent.com/20601160/215523653-37e88e4d-87bb-4908-b5d6-3b4213177bd1.PNG)

**Comment by jamesros161** [comment]
Closing this ticket, since this can easily be resolved by adding the 'mod-reset' class to any 'p' tags in which this padding is not desired. Otherwise, removing this CSS rule would break the right aligned text padding on full width pages & containers
