### ISSUE TITLE
Selecting transparent color color palette causes css syntax error

### ISSUE THREAD

**Issue by W3ap0n-X** [BoldGrid/crio#66]
Selecting transparent color color palette causes css syntax error in Crio 2.20.1

1. Go to Customize → Color Palette
2. Click on any color in the palette 
3. set the alpha slider to any value below 100 
4. Publish and refresh

**Comment by jamesros161** [comment]
The following picture represents Crio Starter Content with normal palette:

![Image](https://user-images.githubusercontent.com/49331357/235994312-7ca39901-dcc8-4111-94b5-73fb1584c545.png)

<hr>

The following picture represents the same content with color-1 set to a alpha lower than 100. Notice the header color is missing now:

![Image](https://user-images.githubusercontent.com/49331357/235994762-dab5ac10-a097-41eb-9a04-bb94fcfc8420.png)

<hr>

Notice as well that when using chrome DevTools to inspect the CSS of the broken site, the :root element shows the broken CSS

![Image](https://user-images.githubusercontent.com/49331357/235995252-709ccc76-27a5-4555-8b49-52f493707d13.png)

<hr>

The Following picture represents the same configuration, but with the patch-fix:

![Image](https://user-images.githubusercontent.com/49331357/235996070-19f3effe-cf4c-4db9-817c-2edc2d6713d9.png)

<hr>

Notice the corrected CSS on the :root element:

![Image](https://user-images.githubusercontent.com/49331357/235996573-77b8ec28-30ac-4140-99da-837e3c624580.png)
