### ISSUE TITLE
PHP8.2 Deprecated: Using ${var} in strings is deprecated, use {$var} instead

### ISSUE THREAD

**Issue by jamesros161** [BoldGrid/crio#81]
`Deprecated: Using ${var} in strings is deprecated, use {$var} instead` notice on php8.2

**Comment by nicolepaschen** [comment]
Pattern backgrounds don't tile properly on the front end
![pattern-background](https://github.com/BoldGrid/crio/assets/20601160/b2d09c77-0cf0-4cec-8529-9e21e0786a18)

**Comment by nicolepaschen** [comment]
Blog > Blog Page > Post Meta
New Lines and Hide do not update the live preview. The front end updates correctly tho.
![live-preview-bug](https://github.com/BoldGrid/crio/assets/20601160/6330385b-3317-49ca-9888-1b8150d66b2f)
